export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO';
export const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS';
export const AGREGAR_PROYECTOS = 'AGREGAR_PROYECTOS';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const ACTUAL_PROYECTO = 'ACTUAL_PROYECTO';
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO';
