export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO';
export const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS';
export const AGREGAR_PROYECTOS = 'AGREGAR_PROYECTOS';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const ACTUAL_PROYECTO = 'ACTUAL_PROYECTO';
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO';
export const PROYECTO_ERROR = 'PROYECTO_ERROR';

export const TAREA_PROYECTOS = 'TAREA_PROYECTOS';
export const AGREGAR_TAREA = 'AGREGAR_TAREA';
export const VALIDAR_TAREA = 'VALIDAR_TAREA';
export const ELIMINAR_TAREA = 'ELIMINAR_TAREA';
export const ESTADO_TAREA = 'ESTADO_TAREA';
export const ACTUAL_TAREA = 'ACTUAL_TAREA';
export const ACTUALIZAR_TAREA = 'ACTUALIZAR_TAREA';
export const LIMPIAR_TAREA = 'LIMPIAR_TAREA';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const REGISTRO_EXITOSO ="REGISTRO_EXITOSO";
export const REGISTRO_ERROR = "REGISTRO_ERROR"; 
export const OBTENER_DATOS = "OBTENER_DATOS"; 
export const LOGIN_EXITOSO ="LOGIN_EXITOSO";
export const LOGIN_ERROR ="LOGIN_ERROR";
export const CERRAR_SESION ="CERRAR_SESION";
